in:
  type: spanner
  auth_method: json_key
  json_key: /path/to/credentials.json
  project_id: test-project
  instance_id: test-instance
  database_id: test-database
  table: test_table
  socket_timeout: 0

out:
  type: stdout
