in:
  type: spanner
  project_id: test-project
  instance_id: test-instance
  database_id: test-database
  table: Singers
  use_emulator: true
  socket_timeout: 0
  column_options:
    SingerInfo: {value_type: string}

out:
  type: stdout
